spring.application.name=workshopmongo

spring.data.mongodb.uri=mongodb://localhost:27017/workshop_mongo

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoClientFactoryBean=DEBUG
